spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/realcool?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: per.real.cool.module.*.entity
  mapper-locations: classpath:mapper/*/*.xml